import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Headar from "./components/Headar";
import Footer from "./components/Footer";
import SessionWrapper from "./components/SessionWrapper";
import toast, { Toaster } from 'react-hot-toast';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <main className=" md:max-w-[80vw] border md:mx-auto p-4 ">
          <SessionWrapper>
            <Toaster />
            <Headar />
            {children}
            <Footer />

          </SessionWrapper>
        </main>

      </body>
    </html>
  );
}
